### ISSUE TITLE
Review file nam_dict.txt

### ISSUE THREAD

**Issue by miquelcamprodon** [lead-ratings/gender-guesser#2]
File nam_dict.txt has not been converted properly when changing the encoding. 
Some lines have less whitespaces than expected.

**Comment by dukebody** [comment]
Thank you for reporting this issue. It probably affects quite a lot of names... Will fix it and make a release soon!

**Comment by dukebody** [comment]
@miquelcamprodon We have released gender-guesser 0.3.0 that fixes this. Enjoy! :D
